version: '3.4'

services:
  addition:
    image: addition
    build:
      context: add
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8090-8092:8090"

  frontend:
    image: front
    build:
      context: front
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure

  gateway:
    image: gateway
    build:
      context: gateway
      dockerfile: ./Dockerfile
    environment:
      - BACKEND_ADD_BASE=http://addition
      - BACKEND_SUB_BASE=http://subtract
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8080-8082:8080"

  subtract:
    image: subtract
    build:
      context: subtract
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8070-8072:8070"

  nginx:
    image: nginx
    build:
      context: loadbalancer
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure