version: '3.4'

services:
  addition:
    image: addition
    build:
      context: add
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8090:8090

  frontend:
    image: front
    build:
      context: front
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  gateway:
    image: gateway
    build:
      context: gateway
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_BASE=http://host.docker.internal

  subtract:
    image: subtract
    build:
      context: subtract
      dockerfile: ./Dockerfile
    ports:
      - "8070:8070"
