version: '3.4'

services:
  addition:
    image: addition
    build:
      context: add
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8090:8090
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
